# Generated by Django 3.0.8 on 2020-07-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20200716_2058'),
    ]

    operations = [
    ]
