# Generated by Django 3.0.8 on 2020-07-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200716_2105'),
    ]

    operations = [
    ]
