# Generated by Django 3.0.8 on 2020-07-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestModel', '0004_auto_20200716_2110'),
    ]

    operations = [

    ]
