# Generated by Django 3.0.8 on 2020-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_feedback_input_product_send_tag'),
    ]

    operations = [

    ]
