# Generated by Django 3.0.8 on 2020-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20200726_0928'),
    ]

    operations = [

    ]
