# Generated by Django 3.0.8 on 2020-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestModel', '0010_feedback_input_product_send_tag'),
    ]

    operations = [
    ]
