# Generated by Django 3.0.8 on 2020-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestModel', '0011_feedback_input_product_send_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('satisfactionvalue', models.IntegerField(default=3)),
                ('sendID', models.IntegerField(default=0)),
                ('receiverID', models.IntegerField(default=0)),
                ('customerID', models.CharField(max_length=50)),
                ('productID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('inputID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('receiverID', models.IntegerField(default=0)),
                ('hobby', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('relationship', models.CharField(max_length=50)),
                ('budget', models.FloatField(default=0)),
                ('occasion', models.CharField(max_length=50)),
                ('customerID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tagID', models.IntegerField(default=0)),
                ('shoppingplatform', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('weblink', models.URLField(max_length=1000)),
                ('productname', models.CharField(max_length=100)),
                ('imagelink', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('sendID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('receiverID', models.IntegerField(default=0)),
                ('customerID', models.CharField(max_length=50)),
                ('productID', models.IntegerField(default=0)),
                ('inputID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('hobby', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('relationship', models.CharField(max_length=50)),
                ('budget', models.FloatField(default=0)),
                ('occasion', models.CharField(max_length=50)),
            ],
        ),
    ]
